services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: dev
    networks:
      default:
        aliases:
          - proarti-test.localhost
          - test.proarti-test.localhost

    volumes:
      - .:/srv

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: babar
      POSTGRES_USER: test

  dockerize:
    image: jwilder/dockerize
