# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  stan:
    docker:
      - image: cacahouete/phpaudit:8.1.3
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer -o composer-setup.php
      - run: php composer-setup.php --filename=composer --install-dir=/usr/local/bin
      - run: rm composer-setup.php
      - run: composer install
      - run: phpstan analyse
  cs:
    docker:
      - image: cacahouete/phpaudit:8.1.3
    steps:
      - checkout
      - run: "php-cs-fixer fix --dry-run --using-cache=no --verbose --diff"
  cpd:
    docker:
      - image: cacahouete/phpaudit:8.1.3
    steps:
      - checkout
      - run: "phpcpd src"
  md:
    docker:
      - image: cacahouete/phpaudit:8.1.3
    steps:
      - checkout
      - run: "phpmd src text .phpmd.xml"
  security:
    docker:
      - image: cacahouete/local-php-security-checker-docker
        entrypoint: []
    steps:
      - checkout
      - run: "local-php-security-checker"

workflows:
  QA:
    jobs:
      - stan
      - cs
      - cpd
      - md
      - security
